import express from "express";

const app = express();
const port = 3000;

const mess = "http://localhost:3000/users";
const mess2 = "http://localhost:3000/contact";

app.get("/", (req,res)=>{
    res.send(
      "hello world! <br>" + 
      "<h1>Heading</h1>" +
      "<a href=" + mess + " >users</a> <br>" +
      "<a href=" + mess2 + " >contact</a>"
    );
    // console.log(req);
    // console.log("____________________________________________________________________________________________");
    // console.log(res);
});

// Making more routes.

app.get("/users", (req,res)=>{
  res.send("<h2> HELLO USER! ANKIT</h2>");
});

app.get("/contact", (req,res) =>{
  res.send("This is my contact details. my phone is (i won't tell you!)");
});


// Note:- req object

/**
 * body
 * method
 * url 
 * params 
 * query 
 * headers
 */

// note res object 

/**
 * send
 * sendFile 
 * json
 * status
 * redirect
 */

app.listen(port, ()=>{
    console.log("The server is listening at port " + port);
});


// This the res object. 

// ____________________________________________________________________________________________
// <ref *1> ServerResponse {
//   _events: [Object: null prototype] { finish: [Function: bound resOnFinish] },
//   _eventsCount: 1,
//   _maxListeners: undefined,
//   outputData: [],
//   outputSize: 0,
//   writable: true,
//   destroyed: false,
//   _last: false,
//   chunkedEncoding: false,
//   shouldKeepAlive: true,
//   maxRequestsOnConnectionReached: false,
//   _defaultKeepAlive: true,
//   useChunkedEncodingByDefault: true,
//   sendDate: true,
//   _removedConnection: false,
//   _removedContLen: true,
//   _removedTE: true,
//   strictContentLength: false,
//   _contentLength: 0,
//   _hasBody: false,
//   _trailer: '',
//   finished: true,
//   _headerSent: true,
//   _closed: false,
//   _header: 'HTTP/1.1 304 Not Modified\r\n' +
//     'X-Powered-By: Express\r\n' +
//     'ETag: W/"c-QwzjTQIHJO11oZbfwq1nx3dy0Wk"\r\n' +
//     'Date: Thu, 05 Mar 2026 14:20:47 GMT\r\n' +
//     'Connection: keep-alive\r\n' +
//     'Keep-Alive: timeout=5\r\n' +
//     '\r\n',
//   _keepAliveTimeout: 5000,
//   _onPendingData: [Function: bound updateOutgoingData],
//   req: IncomingMessage {
//     _events: {
//       close: undefined,
//       error: undefined,
//       data: undefined,
//       end: undefined,
//       readable: undefined
//     },
//     _readableState: ReadableState {
//       highWaterMark: 16384,
//       buffer: [],
//       bufferIndex: 0,
//       length: 0,
//       pipes: [],
//       awaitDrainWriters: null,
//       [Symbol(kState)]: 1315084
//     },
//     _maxListeners: undefined,
//     socket: Socket {
//       connecting: false,
//       _hadError: false,
//       _parent: null,
//       _host: null,
//       _closeAfterHandlingError: false,
//       _events: [Object],
//       _readableState: [ReadableState],
//       _writableState: [WritableState],
//       allowHalfOpen: true,
//       _maxListeners: undefined,
//       _eventsCount: 8,
//       _sockname: null,
//       _pendingData: null,
//       _pendingEncoding: '',
//       server: [Server],
//       _server: [Server],
//       parser: [HTTPParser],
//       on: [Function: socketListenerWrap],
//       addListener: [Function: socketListenerWrap],
//       prependListener: [Function: socketListenerWrap],
//       setEncoding: [Function: socketSetEncoding],
//       _paused: false,
//       _httpMessage: [Circular *1],
//       [Symbol(async_id_symbol)]: 14,
//       [Symbol(kHandle)]: [TCP],
//       [Symbol(lastWriteQueueSize)]: 0,
//       [Symbol(timeout)]: null,
//       [Symbol(kBuffer)]: null,
//       [Symbol(kBufferCb)]: null,
//       [Symbol(kBufferGen)]: null,
//       [Symbol(shapeMode)]: true,
//       [Symbol(kCapture)]: false,
//       [Symbol(kSetNoDelay)]: true,
//       [Symbol(kSetKeepAlive)]: false,
//       [Symbol(kSetKeepAliveInitialDelay)]: 0,
//       [Symbol(kBytesRead)]: 0,
//       [Symbol(kBytesWritten)]: 0
//     },
//     httpVersionMajor: 1,
//     httpVersionMinor: 1,
//     httpVersion: '1.1',
//     complete: false,
//     rawHeaders: [
//       'Host',
//       'localhost:3000',
//       'Connection',
//       'keep-alive',
//       'Cache-Control',
//       'max-age=0',
//       'sec-ch-ua',
//       '"Not:A-Brand";v="99", "Google Chrome";v="145", "Chromium";v="145"',
//       'sec-ch-ua-mobile',
//       '?0',
//       'sec-ch-ua-platform',
//       '"Windows"',
//       'Upgrade-Insecure-Requests',
//       '1',
//       'User-Agent',
//       'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36',
//       'Accept',
//       'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
//       'Sec-Fetch-Site',
//       'none',
//       'Sec-Fetch-Mode',
//       'navigate',
//       'Sec-Fetch-User',
//       '?1',
//       'Sec-Fetch-Dest',
//       'document',
//       'Accept-Encoding',
//       'gzip, deflate, br, zstd',
//       'Accept-Language',
//       'en-US,en;q=0.9',
//       'If-None-Match',
//       'W/"c-QwzjTQIHJO11oZbfwq1nx3dy0Wk"'
//     ],
//     rawTrailers: [],
//     joinDuplicateHeaders: null,
//     aborted: false,
//     upgrade: false,
//     url: '/',
//     method: 'GET',
//     statusCode: null,
//     statusMessage: null,
//     client: Socket {
//       connecting: false,
//       _hadError: false,
//       _parent: null,
//       _host: null,
//       _closeAfterHandlingError: false,
//       _events: [Object],
//       _readableState: [ReadableState],
//       _writableState: [WritableState],
//       allowHalfOpen: true,
//       _maxListeners: undefined,
//       _eventsCount: 8,
//       _sockname: null,
//       _pendingData: null,
//       _pendingEncoding: '',
//       server: [Server],
//       _server: [Server],
//       parser: [HTTPParser],
//       on: [Function: socketListenerWrap],
//       addListener: [Function: socketListenerWrap],
//       prependListener: [Function: socketListenerWrap],
//       setEncoding: [Function: socketSetEncoding],
//       _paused: false,
//       _httpMessage: [Circular *1],
//       [Symbol(async_id_symbol)]: 14,
//       [Symbol(kHandle)]: [TCP],
//       [Symbol(lastWriteQueueSize)]: 0,
//       [Symbol(timeout)]: null,
//       [Symbol(kBuffer)]: null,
//       [Symbol(kBufferCb)]: null,
//       [Symbol(kBufferGen)]: null,
//       [Symbol(shapeMode)]: true,
//       [Symbol(kCapture)]: false,
//       [Symbol(kSetNoDelay)]: true,
//       [Symbol(kSetKeepAlive)]: false,
//       [Symbol(kSetKeepAliveInitialDelay)]: 0,
//       [Symbol(kBytesRead)]: 0,
//       [Symbol(kBytesWritten)]: 0
//     },
//     _consuming: false,
//     _dumped: false,
//     res: [Circular *1],
//     next: [Function: next],
//     baseUrl: '',
//     originalUrl: '/',
//     _parsedUrl: Url {
//       protocol: null,
//       slashes: null,
//       auth: null,
//       host: null,
//       port: null,
//       hostname: null,
//       hash: null,
//       search: null,
//       query: null,
//       pathname: '/',
//       path: '/',
//       href: '/',
//       _raw: '/'
//     },
//     route: Route {
//       path: '/',
//       stack: [Array],
//       methods: [Object: null prototype]
//     },
//     params: [Object: null prototype] {},
//     [Symbol(shapeMode)]: true,
//     [Symbol(kCapture)]: false,
//     [Symbol(kHeaders)]: {
//       host: 'localhost:3000',
//       connection: 'keep-alive',
//       'cache-control': 'max-age=0',
//       'sec-ch-ua': '"Not:A-Brand";v="99", "Google Chrome";v="145", "Chromium";v="145"',
//       'sec-ch-ua-mobile': '?0',
//       'sec-ch-ua-platform': '"Windows"',
//       'upgrade-insecure-requests': '1',
//       'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36',       
//       accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
//       'sec-fetch-site': 'none',
//       'sec-fetch-mode': 'navigate',
//       'sec-fetch-user': '?1',
//       'sec-fetch-dest': 'document',
//       'accept-encoding': 'gzip, deflate, br, zstd',
//       'accept-language': 'en-US,en;q=0.9',
//       'if-none-match': 'W/"c-QwzjTQIHJO11oZbfwq1nx3dy0Wk"'
//     },
//     [Symbol(kHeadersCount)]: 32,
//     [Symbol(kTrailers)]: null,
//     [Symbol(kTrailersCount)]: 0
//   },
//   _sent100: false,
//   _expect_continue: false,
//   _maxRequestsPerSocket: 0,
//   locals: [Object: null prototype] {},
//   statusCode: 304,
//   statusMessage: 'Not Modified',
//   [Symbol(shapeMode)]: false,
//   [Symbol(kCapture)]: false,
//   [Symbol(kBytesWritten)]: 0,
//   [Symbol(kNeedDrain)]: false,
//   [Symbol(corked)]: 0,
//   [Symbol(kChunkedBuffer)]: [],
//   [Symbol(kChunkedLength)]: 0,
//   [Symbol(kSocket)]: <ref *2> Socket {
//     connecting: false,
//     _hadError: false,
//     _parent: null,
//     _host: null,
//     _closeAfterHandlingError: false,
//     _events: {
//       close: [Array],
//       error: [Function: socketOnError],
//       prefinish: undefined,
//       finish: undefined,
//       drain: [Function: bound socketOnDrain],
//       data: [Function: bound socketOnData],
//       end: [Array],
//       readable: undefined,
//       timeout: [Function: socketOnTimeout],
//       resume: [Function: onSocketResume],
//       pause: [Function: onSocketPause]
//     },
//     _readableState: ReadableState {
//       highWaterMark: 16384,
//       buffer: [],
//       bufferIndex: 0,
//       length: 0,
//       pipes: [],
//       awaitDrainWriters: null,
//       [Symbol(kState)]: 193997060
//     },
//     _writableState: WritableState {
//       highWaterMark: 16384,
//       length: 0,
//       corked: 0,
//       onwrite: [Function: bound onwrite],
//       writelen: 0,
//       bufferedIndex: 0,
//       pendingcb: 1,
//       [Symbol(kState)]: 420217092,
//       [Symbol(kBufferedValue)]: null,
//       [Symbol(kWriteCbValue)]: null,
//       [Symbol(kAfterWriteTickInfoValue)]: [Object]
//     },
//     allowHalfOpen: true,
//     _maxListeners: undefined,
//     _eventsCount: 8,
//     _sockname: null,
//     _pendingData: null,
//     _pendingEncoding: '',
//     server: Server {
//       maxHeaderSize: undefined,
//       insecureHTTPParser: undefined,
//       requestTimeout: 300000,
//       headersTimeout: 60000,
//       keepAliveTimeout: 5000,
//       keepAliveTimeoutBuffer: 1000,
//       connectionsCheckingInterval: 30000,
//       requireHostHeader: true,
//       joinDuplicateHeaders: undefined,
//       rejectNonStandardBodyWrites: false,
//       shouldUpgradeCallback: [Function (anonymous)],
//       _events: [Object: null prototype],
//       _eventsCount: 4,
//       _maxListeners: undefined,
//       _connections: 1,
//       _handle: [TCP],
//       _usingWorkers: false,
//       _workers: [],
//       _unref: false,
//       _listeningId: 2,
//       allowHalfOpen: true,
//       pauseOnConnect: false,
//       noDelay: true,
//       keepAlive: false,
//       keepAliveInitialDelay: 0,
//       highWaterMark: 16384,
//       httpAllowHalfOpen: false,
//       timeout: 0,
//       maxHeadersCount: null,
//       maxRequestsPerSocket: 0,
//       _connectionKey: '6::::3000',
//       [Symbol(IncomingMessage)]: [Function: IncomingMessage],
//       [Symbol(ServerResponse)]: [Function: ServerResponse],
//       [Symbol(shapeMode)]: false,
//       [Symbol(kCapture)]: false,
//       [Symbol(async_id_symbol)]: 8,
//       [Symbol(kUniqueHeaders)]: null,
//       [Symbol(http.server.connections)]: ConnectionsList {},
//       [Symbol(http.server.connectionsCheckingInterval)]: Timeout {
//         _idleTimeout: 30000,
//         _idlePrev: [TimersList],
//         _idleNext: [TimersList],
//         _idleStart: 235,
//         _onTimeout: [Function: bound checkConnections],
//         _timerArgs: undefined,
//         _repeat: 30000,
//         _destroyed: false,
//         [Symbol(refed)]: false,
//         [Symbol(kHasPrimitive)]: false,
//         [Symbol(asyncId)]: 10,
//         [Symbol(triggerId)]: 9,
//         [Symbol(kAsyncContextFrame)]: undefined
//       }
//     },
//     _server: Server {
//       maxHeaderSize: undefined,
//       insecureHTTPParser: undefined,
//       requestTimeout: 300000,
//       headersTimeout: 60000,
//       keepAliveTimeout: 5000,
//       keepAliveTimeoutBuffer: 1000,
//       connectionsCheckingInterval: 30000,
//       requireHostHeader: true,
//       joinDuplicateHeaders: undefined,
//       rejectNonStandardBodyWrites: false,
//       shouldUpgradeCallback: [Function (anonymous)],
//       _events: [Object: null prototype],
//       _eventsCount: 4,
//       _maxListeners: undefined,
//       _connections: 1,
//       _handle: [TCP],
//       _usingWorkers: false,
//       _workers: [],
//       _unref: false,
//       _listeningId: 2,
//       allowHalfOpen: true,
//       pauseOnConnect: false,
//       noDelay: true,
//       keepAlive: false,
//       keepAliveInitialDelay: 0,
//       highWaterMark: 16384,
//       httpAllowHalfOpen: false,
//       timeout: 0,
//       maxHeadersCount: null,
//       maxRequestsPerSocket: 0,
//       _connectionKey: '6::::3000',
//       [Symbol(IncomingMessage)]: [Function: IncomingMessage],
//       [Symbol(ServerResponse)]: [Function: ServerResponse],
//       [Symbol(shapeMode)]: false,
//       [Symbol(kCapture)]: false,
//       [Symbol(async_id_symbol)]: 8,
//       [Symbol(kUniqueHeaders)]: null,
//       [Symbol(http.server.connections)]: ConnectionsList {},
//       [Symbol(http.server.connectionsCheckingInterval)]: Timeout {
//         _idleTimeout: 30000,
//         _idlePrev: [TimersList],
//         _idleNext: [TimersList],
//         _idleStart: 235,
//         _onTimeout: [Function: bound checkConnections],
//         _timerArgs: undefined,
//         _repeat: 30000,
//         _destroyed: false,
//         [Symbol(refed)]: false,
//         [Symbol(kHasPrimitive)]: false,
//         [Symbol(asyncId)]: 10,
//         [Symbol(triggerId)]: 9,
//         [Symbol(kAsyncContextFrame)]: undefined
//       }
//     },
//     parser: HTTPParser {
//       '0': null,
//       '1': [Function: parserOnHeaders],
//       '2': [Function: parserOnHeadersComplete],
//       '3': [Function: parserOnBody],
//       '4': [Function: parserOnMessageComplete],
//       '5': [Function: bound onParserExecute],
//       '6': [Function: bound onParserTimeout],
//       _headers: [],
//       _url: '',
//       socket: [Circular *2],
//       incoming: [IncomingMessage],
//       outgoing: null,
//       maxHeaderPairs: 2000,
//       _consumed: true,
//       onIncoming: [Function: bound parserOnIncoming],
//       joinDuplicateHeaders: null,
//       [Symbol(resource_symbol)]: [HTTPServerAsyncResource]
//     },
//     on: [Function: socketListenerWrap],
//     addListener: [Function: socketListenerWrap],
//     prependListener: [Function: socketListenerWrap],
//     setEncoding: [Function: socketSetEncoding],
//     _paused: false,
//     _httpMessage: [Circular *1],
//     [Symbol(async_id_symbol)]: 14,
//     [Symbol(kHandle)]: TCP {
//       reading: true,
//       onconnection: null,
//       _consumed: true,
//       [Symbol(owner_symbol)]: [Circular *2]
//     },
//     [Symbol(lastWriteQueueSize)]: 0,
//     [Symbol(timeout)]: null,
//     [Symbol(kBuffer)]: null,
//     [Symbol(kBufferCb)]: null,
//     [Symbol(kBufferGen)]: null,
//     [Symbol(shapeMode)]: true,
//     [Symbol(kCapture)]: false,
//     [Symbol(kSetNoDelay)]: true,
//     [Symbol(kSetKeepAlive)]: false,
//     [Symbol(kSetKeepAliveInitialDelay)]: 0,
//     [Symbol(kBytesRead)]: 0,
//     [Symbol(kBytesWritten)]: 0
//   },
//   [Symbol(kOutHeaders)]: [Object: null prototype] {
//     'x-powered-by': [ 'X-Powered-By', 'Express' ],
//     etag: [ 'ETag', 'W/"c-QwzjTQIHJO11oZbfwq1nx3dy0Wk"' ]
//   },
//   [Symbol(errored)]: null,
//   [Symbol(kHighWaterMark)]: 16384,
//   [Symbol(kRejectNonStandardBodyWrites)]: false,
//   [Symbol(kUniqueHeaders)]: null
// }

// this is the req object. 

/* <ref *2> IncomingMessage {
  _events: {
    close: undefined,
    error: undefined,
    data: undefined,
    end: undefined,
    readable: undefined
  },
  _readableState: ReadableState {
    highWaterMark: 16384,
    buffer: [],
    bufferIndex: 0,
    length: 0,
    pipes: [],
    awaitDrainWriters: null,
    [Symbol(kState)]: 1315084
  },
  _maxListeners: undefined,
  socket: <ref *1> Socket {
    connecting: false,
    _hadError: false,
    _parent: null,
    _host: null,
    _closeAfterHandlingError: false,
    _events: {
      close: [Array],
      error: [Function: socketOnError],
      prefinish: undefined,
      finish: undefined,
      drain: [Function: bound socketOnDrain],
      data: [Function: bound socketOnData],
      end: [Array],
      readable: undefined,
      timeout: [Function: socketOnTimeout],
      resume: [Function: onSocketResume],
      pause: [Function: onSocketPause]
    },
    _readableState: ReadableState {
      highWaterMark: 16384,
      buffer: [],
      bufferIndex: 0,
      length: 0,
      pipes: [],
      awaitDrainWriters: null,
      [Symbol(kState)]: 193997060
    },
    _writableState: WritableState {
      highWaterMark: 16384,
      length: 0,
      corked: 0,
      onwrite: [Function: bound onwrite],
      writelen: 0,
      bufferedIndex: 0,
      pendingcb: 1,
      [Symbol(kState)]: 420217092,
      [Symbol(kBufferedValue)]: null,
      [Symbol(kWriteCbValue)]: null,
      [Symbol(kAfterWriteTickInfoValue)]: [Object]
    },
    allowHalfOpen: true,
    _maxListeners: undefined,
    _eventsCount: 8,
    _sockname: null,
    _pendingData: null,
    _pendingEncoding: '',
    server: Server {
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      requestTimeout: 300000,
      headersTimeout: 60000,
      keepAliveTimeout: 5000,
      keepAliveTimeoutBuffer: 1000,
      connectionsCheckingInterval: 30000,
      requireHostHeader: true,
      joinDuplicateHeaders: undefined,
      rejectNonStandardBodyWrites: false,
      shouldUpgradeCallback: [Function (anonymous)],
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      _connections: 2,
      _handle: [TCP],
      _usingWorkers: false,
      _workers: [],
      _unref: false,
      _listeningId: 2,
      allowHalfOpen: true,
      pauseOnConnect: false,
      noDelay: true,
      keepAlive: false,
      keepAliveInitialDelay: 0,
      highWaterMark: 16384,
      httpAllowHalfOpen: false,
      timeout: 0,
      maxHeadersCount: null,
      maxRequestsPerSocket: 0,
      _connectionKey: '6::::3000',
      [Symbol(IncomingMessage)]: [Function: IncomingMessage],
      [Symbol(ServerResponse)]: [Function: ServerResponse],
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false,
      [Symbol(async_id_symbol)]: 8,
      [Symbol(kUniqueHeaders)]: null,
      [Symbol(http.server.connections)]: ConnectionsList {},
      [Symbol(http.server.connectionsCheckingInterval)]: Timeout {
        _idleTimeout: 30000,
        _idlePrev: [TimersList],
        _idleNext: [TimersList],
        _idleStart: 204,
        _onTimeout: [Function: bound checkConnections],
        _timerArgs: undefined,
        _repeat: 30000,
        _destroyed: false,
        [Symbol(refed)]: false,
        [Symbol(kHasPrimitive)]: false,
        [Symbol(asyncId)]: 10,
        [Symbol(triggerId)]: 9,
        [Symbol(kAsyncContextFrame)]: undefined
      }
    },
    _server: Server {
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      requestTimeout: 300000,
      headersTimeout: 60000,
      keepAliveTimeout: 5000,
      keepAliveTimeoutBuffer: 1000,
      connectionsCheckingInterval: 30000,
      requireHostHeader: true,
      joinDuplicateHeaders: undefined,
      rejectNonStandardBodyWrites: false,
      shouldUpgradeCallback: [Function (anonymous)],
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      _connections: 2,
      _handle: [TCP],
      _usingWorkers: false,
      _workers: [],
      _unref: false,
      _listeningId: 2,
      allowHalfOpen: true,
      pauseOnConnect: false,
      noDelay: true,
      keepAlive: false,
      keepAliveInitialDelay: 0,
      highWaterMark: 16384,
      httpAllowHalfOpen: false,
      timeout: 0,
      maxHeadersCount: null,
      maxRequestsPerSocket: 0,
      _connectionKey: '6::::3000',
      [Symbol(IncomingMessage)]: [Function: IncomingMessage],
      [Symbol(ServerResponse)]: [Function: ServerResponse],
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false,
      [Symbol(async_id_symbol)]: 8,
      [Symbol(kUniqueHeaders)]: null,
      [Symbol(http.server.connections)]: ConnectionsList {},
      [Symbol(http.server.connectionsCheckingInterval)]: Timeout {
        _idleTimeout: 30000,
        _idlePrev: [TimersList],
        _idleNext: [TimersList],
        _idleStart: 204,
        _onTimeout: [Function: bound checkConnections],
        _timerArgs: undefined,
        _repeat: 30000,
        _destroyed: false,
        [Symbol(refed)]: false,
        [Symbol(kHasPrimitive)]: false,
        [Symbol(asyncId)]: 10,
        [Symbol(triggerId)]: 9,
        [Symbol(kAsyncContextFrame)]: undefined
      }
    },
    parser: HTTPParser {
      '0': null,
      '1': [Function: parserOnHeaders],
      '2': [Function: parserOnHeadersComplete],
      '3': [Function: parserOnBody],
      '4': [Function: parserOnMessageComplete],
      '5': [Function: bound onParserExecute],
      '6': [Function: bound onParserTimeout],
      _headers: [],
      _url: '',
      socket: [Circular *1],
      incoming: [Circular *2],
      outgoing: null,
      maxHeaderPairs: 2000,
      _consumed: true,
      onIncoming: [Function: bound parserOnIncoming],
      joinDuplicateHeaders: null,
      [Symbol(resource_symbol)]: [HTTPServerAsyncResource]
    },
    on: [Function: socketListenerWrap],
    addListener: [Function: socketListenerWrap],
    prependListener: [Function: socketListenerWrap],
    setEncoding: [Function: socketSetEncoding],
    _paused: false,
    _httpMessage: ServerResponse {
      _events: [Object: null prototype],
      _eventsCount: 1,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: false,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: true,
      _removedConnection: false,
      _removedContLen: true,
      _removedTE: true,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: false,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      _header: 'HTTP/1.1 304 Not Modified\r\n' +
        'X-Powered-By: Express\r\n' +
        'ETag: W/"c-QwzjTQIHJO11oZbfwq1nx3dy0Wk"\r\n' +
        'Date: Thu, 05 Mar 2026 14:24:30 GMT\r\n' +
        'Connection: keep-alive\r\n' +
        'Keep-Alive: timeout=5\r\n' +
        '\r\n',
      _keepAliveTimeout: 5000,
      _onPendingData: [Function: bound updateOutgoingData],
      req: [Circular *2],
      _sent100: false,
      _expect_continue: false,
      _maxRequestsPerSocket: 0,
      locals: [Object: null prototype] {},
      statusCode: 304,
      statusMessage: 'Not Modified',
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kChunkedBuffer)]: [],
      [Symbol(kChunkedLength)]: 0,
      [Symbol(kSocket)]: [Circular *1],
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    [Symbol(async_id_symbol)]: 17,
    [Symbol(kHandle)]: TCP {
      reading: true,
      onconnection: null,
      _consumed: true,
      [Symbol(owner_symbol)]: [Circular *1]
    },
    [Symbol(lastWriteQueueSize)]: 0,
    [Symbol(timeout)]: null,
    [Symbol(kBuffer)]: null,
    [Symbol(kBufferCb)]: null,
    [Symbol(kBufferGen)]: null,
    [Symbol(shapeMode)]: true,
    [Symbol(kCapture)]: false,
    [Symbol(kSetNoDelay)]: true,
    [Symbol(kSetKeepAlive)]: false,
    [Symbol(kSetKeepAliveInitialDelay)]: 0,
    [Symbol(kBytesRead)]: 0,
    [Symbol(kBytesWritten)]: 0
  },
  httpVersionMajor: 1,
  httpVersionMinor: 1,
  httpVersion: '1.1',
  complete: false,
  rawHeaders: [
    'Host',
    'localhost:3000',
    'Connection',
    'keep-alive',
    'Cache-Control',
    'max-age=0',
    'sec-ch-ua',
    '"Not:A-Brand";v="99", "Google Chrome";v="145", "Chromium";v="145"',
    'sec-ch-ua-mobile',
    '?0',
    'sec-ch-ua-platform',
    '"Windows"',
    'Upgrade-Insecure-Requests',
    '1',
    'User-Agent',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36',
    'Accept',
    // 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,;q=0.8,application/signed-exchange;v=b3;q=0.7',
//     'Sec-Fetch-Site',
//     'none',
//     'Sec-Fetch-Mode',
//     'navigate',
//     'Sec-Fetch-User',
//     '?1',
//     'Sec-Fetch-Dest',
//     'document',
//     'Accept-Encoding',
//     'gzip, deflate, br, zstd',
//     'Accept-Language',
//     'en-US,en;q=0.9',
//     'If-None-Match',
//     'W/"c-QwzjTQIHJO11oZbfwq1nx3dy0Wk"'
//   ],
//   rawTrailers: [],
//   joinDuplicateHeaders: null,
//   aborted: false,
//   upgrade: false,
//   url: '/',
//   method: 'GET',
//   statusCode: null,
//   statusMessage: null,
//   client: <ref *1> Socket {
//     connecting: false,
//     _hadError: false,
//     _parent: null,
//     _host: null,
//     _closeAfterHandlingError: false,
//     _events: {
//       close: [Array],
//       error: [Function: socketOnError],
//       prefinish: undefined,
//       finish: undefined,
//       drain: [Function: bound socketOnDrain],
//       data: [Function: bound socketOnData],
//       end: [Array],
//       readable: undefined,
//       timeout: [Function: socketOnTimeout],
//       resume: [Function: onSocketResume],
//       pause: [Function: onSocketPause]
//     },
//     _readableState: ReadableState {
//       highWaterMark: 16384,
//       buffer: [],
//       bufferIndex: 0,
//       length: 0,
//       pipes: [],
//       awaitDrainWriters: null,
//       [Symbol(kState)]: 193997060
//     },
//     _writableState: WritableState {
//       highWaterMark: 16384,
//       length: 0,
//       corked: 0,
//       onwrite: [Function: bound onwrite],
//       writelen: 0,
//       bufferedIndex: 0,
//       pendingcb: 1,
//       [Symbol(kState)]: 420217092,
//       [Symbol(kBufferedValue)]: null,
//       [Symbol(kWriteCbValue)]: null,
//       [Symbol(kAfterWriteTickInfoValue)]: [Object]
//     },
//     allowHalfOpen: true,
//     _maxListeners: undefined,
//     _eventsCount: 8,
//     _sockname: null,
//     _pendingData: null,
//     _pendingEncoding: '',
//     server: Server {
//       maxHeaderSize: undefined,
//       insecureHTTPParser: undefined,
//       requestTimeout: 300000,
//       headersTimeout: 60000,
//       keepAliveTimeout: 5000,
//       keepAliveTimeoutBuffer: 1000,
//       connectionsCheckingInterval: 30000,
//       requireHostHeader: true,
//       joinDuplicateHeaders: undefined,
//       rejectNonStandardBodyWrites: false,
//       shouldUpgradeCallback: [Function (anonymous)],
//       _events: [Object: null prototype],
//       _eventsCount: 4,
//       _maxListeners: undefined,
//       _connections: 2,
//       _handle: [TCP],
//       _usingWorkers: false,
//       _workers: [],
//       _unref: false,
//       _listeningId: 2,
//       allowHalfOpen: true,
//       pauseOnConnect: false,
//       noDelay: true,
//       keepAlive: false,
//       keepAliveInitialDelay: 0,
//       highWaterMark: 16384,
//       httpAllowHalfOpen: false,
//       timeout: 0,
//       maxHeadersCount: null,
//       maxRequestsPerSocket: 0,
//       _connectionKey: '6::::3000',
//       [Symbol(IncomingMessage)]: [Function: IncomingMessage],
//       [Symbol(ServerResponse)]: [Function: ServerResponse],
//       [Symbol(shapeMode)]: false,
//       [Symbol(kCapture)]: false,
//       [Symbol(async_id_symbol)]: 8,
//       [Symbol(kUniqueHeaders)]: null,
//       [Symbol(http.server.connections)]: ConnectionsList {},
//       [Symbol(http.server.connectionsCheckingInterval)]: Timeout {
//         _idleTimeout: 30000,
//         _idlePrev: [TimersList],
//         _idleNext: [TimersList],
//         _idleStart: 204,
//         _onTimeout: [Function: bound checkConnections],
//         _timerArgs: undefined,
//         _repeat: 30000,
//         _destroyed: false,
//         [Symbol(refed)]: false,
//         [Symbol(kHasPrimitive)]: false,
//         [Symbol(asyncId)]: 10,
//         [Symbol(triggerId)]: 9,
//         [Symbol(kAsyncContextFrame)]: undefined
//       }
//     },
//     _server: Server {
//       maxHeaderSize: undefined,
//       insecureHTTPParser: undefined,
//       requestTimeout: 300000,
//       headersTimeout: 60000,
//       keepAliveTimeout: 5000,
//       keepAliveTimeoutBuffer: 1000,
//       connectionsCheckingInterval: 30000,
//       requireHostHeader: true,
//       joinDuplicateHeaders: undefined,
//       rejectNonStandardBodyWrites: false,
//       shouldUpgradeCallback: [Function (anonymous)],
//       _events: [Object: null prototype],
//       _eventsCount: 4,
//       _maxListeners: undefined,
//       _connections: 2,
//       _handle: [TCP],
//       _usingWorkers: false,
//       _workers: [],
//       _unref: false,
//       _listeningId: 2,
//       allowHalfOpen: true,
//       pauseOnConnect: false,
//       noDelay: true,
//       keepAlive: false,
//       keepAliveInitialDelay: 0,
//       highWaterMark: 16384,
//       httpAllowHalfOpen: false,
//       timeout: 0,
//       maxHeadersCount: null,
//       maxRequestsPerSocket: 0,
//       _connectionKey: '6::::3000',
//       [Symbol(IncomingMessage)]: [Function: IncomingMessage],
//       [Symbol(ServerResponse)]: [Function: ServerResponse],
//       [Symbol(shapeMode)]: false,
//       [Symbol(kCapture)]: false,
//       [Symbol(async_id_symbol)]: 8,
//       [Symbol(kUniqueHeaders)]: null,
//       [Symbol(http.server.connections)]: ConnectionsList {},
//       [Symbol(http.server.connectionsCheckingInterval)]: Timeout {
//         _idleTimeout: 30000,
//         _idlePrev: [TimersList],
//         _idleNext: [TimersList],
//         _idleStart: 204,
//         _onTimeout: [Function: bound checkConnections],
//         _timerArgs: undefined,
//         _repeat: 30000,
//         _destroyed: false,
//         [Symbol(refed)]: false,
//         [Symbol(kHasPrimitive)]: false,
//         [Symbol(asyncId)]: 10,
//         [Symbol(triggerId)]: 9,
//         [Symbol(kAsyncContextFrame)]: undefined
//       }
//     },
//     parser: HTTPParser {
//       '0': null,
//       '1': [Function: parserOnHeaders],
//       '2': [Function: parserOnHeadersComplete],
//       '3': [Function: parserOnBody],
//       '4': [Function: parserOnMessageComplete],
//       '5': [Function: bound onParserExecute],
//       '6': [Function: bound onParserTimeout],
//       _headers: [],
//       _url: '',
//       socket: [Circular *1],
//       incoming: [Circular *2],
//       outgoing: null,
//       maxHeaderPairs: 2000,
//       _consumed: true,
//       onIncoming: [Function: bound parserOnIncoming],
//       joinDuplicateHeaders: null,
//       [Symbol(resource_symbol)]: [HTTPServerAsyncResource]
//     },
//     on: [Function: socketListenerWrap],
//     addListener: [Function: socketListenerWrap],
//     prependListener: [Function: socketListenerWrap],
//     setEncoding: [Function: socketSetEncoding],
//     _paused: false,
//     _httpMessage: ServerResponse {
//       _events: [Object: null prototype],
//       _eventsCount: 1,
//       _maxListeners: undefined,
//       outputData: [],
//       outputSize: 0,
//       writable: true,
//       destroyed: false,
//       _last: false,
//       chunkedEncoding: false,
//       shouldKeepAlive: true,
//       maxRequestsOnConnectionReached: false,
//       _defaultKeepAlive: true,
//       useChunkedEncodingByDefault: true,
//       sendDate: true,
//       _removedConnection: false,
//       _removedContLen: true,
//       _removedTE: true,
//       strictContentLength: false,
//       _contentLength: 0,
//       _hasBody: false,
//       _trailer: '',
//       finished: true,
//       _headerSent: true,
//       _closed: false,
//       _header: 'HTTP/1.1 304 Not Modified\r\n' +
//         'X-Powered-By: Express\r\n' +
//         'ETag: W/"c-QwzjTQIHJO11oZbfwq1nx3dy0Wk"\r\n' +
//         'Date: Thu, 05 Mar 2026 14:24:30 GMT\r\n' +
//         'Connection: keep-alive\r\n' +
//         'Keep-Alive: timeout=5\r\n' +
//         '\r\n',
//       _keepAliveTimeout: 5000,
//       _onPendingData: [Function: bound updateOutgoingData],
//       req: [Circular *2],
//       _sent100: false,
//       _expect_continue: false,
//       _maxRequestsPerSocket: 0,
//       locals: [Object: null prototype] {},
//       statusCode: 304,
//       statusMessage: 'Not Modified',
//       [Symbol(shapeMode)]: false,
//       [Symbol(kCapture)]: false,
//       [Symbol(kBytesWritten)]: 0,
//       [Symbol(kNeedDrain)]: false,
//       [Symbol(corked)]: 0,
//       [Symbol(kChunkedBuffer)]: [],
//       [Symbol(kChunkedLength)]: 0,
//       [Symbol(kSocket)]: [Circular *1],
//       [Symbol(kOutHeaders)]: [Object: null prototype],
//       [Symbol(errored)]: null,
//       [Symbol(kHighWaterMark)]: 16384,
//       [Symbol(kRejectNonStandardBodyWrites)]: false,
//       [Symbol(kUniqueHeaders)]: null
//     },
//     [Symbol(async_id_symbol)]: 17,
//     [Symbol(kHandle)]: TCP {
//       reading: true,
//       onconnection: null,
//       _consumed: true,
//       [Symbol(owner_symbol)]: [Circular *1]
//     },
//     [Symbol(lastWriteQueueSize)]: 0,
//     [Symbol(timeout)]: null,
//     [Symbol(kBuffer)]: null,
//     [Symbol(kBufferCb)]: null,
//     [Symbol(kBufferGen)]: null,
//     [Symbol(shapeMode)]: true,
//     [Symbol(kCapture)]: false,
//     [Symbol(kSetNoDelay)]: true,
//     [Symbol(kSetKeepAlive)]: false,
//     [Symbol(kSetKeepAliveInitialDelay)]: 0,
//     [Symbol(kBytesRead)]: 0,
//     [Symbol(kBytesWritten)]: 0
//   },
//   _consuming: false,
//   _dumped: false,
//   res: <ref *3> ServerResponse {
//     _events: [Object: null prototype] { finish: [Function: bound resOnFinish] },
//     _eventsCount: 1,
//     _maxListeners: undefined,
//     outputData: [],
//     outputSize: 0,
//     writable: true,
//     destroyed: false,
//     _last: false,
//     chunkedEncoding: false,
//     shouldKeepAlive: true,
//     maxRequestsOnConnectionReached: false,
//     _defaultKeepAlive: true,
//     useChunkedEncodingByDefault: true,
//     sendDate: true,
//     _removedConnection: false,
//     _removedContLen: true,
//     _removedTE: true,
//     strictContentLength: false,
//     _contentLength: 0,
//     _hasBody: false,
//     _trailer: '',
//     finished: true,
//     _headerSent: true,
//     _closed: false,
//     _header: 'HTTP/1.1 304 Not Modified\r\n' +
//       'X-Powered-By: Express\r\n' +
//       'ETag: W/"c-QwzjTQIHJO11oZbfwq1nx3dy0Wk"\r\n' +
//       'Date: Thu, 05 Mar 2026 14:24:30 GMT\r\n' +
//       'Connection: keep-alive\r\n' +
//       'Keep-Alive: timeout=5\r\n' +
//       '\r\n',
//     _keepAliveTimeout: 5000,
//     _onPendingData: [Function: bound updateOutgoingData],
//     req: [Circular *2],
//     _sent100: false,
//     _expect_continue: false,
//     _maxRequestsPerSocket: 0,
//     locals: [Object: null prototype] {},
//     statusCode: 304,
//     statusMessage: 'Not Modified',
//     [Symbol(shapeMode)]: false,
//     [Symbol(kCapture)]: false,
//     [Symbol(kBytesWritten)]: 0,
//     [Symbol(kNeedDrain)]: false,
//     [Symbol(corked)]: 0,
//     [Symbol(kChunkedBuffer)]: [],
//     [Symbol(kChunkedLength)]: 0,
//     [Symbol(kSocket)]: <ref *1> Socket {
//       connecting: false,
//       _hadError: false,
//       _parent: null,
//       _host: null,
//       _closeAfterHandlingError: false,
//       _events: [Object],
//       _readableState: [ReadableState],
//       _writableState: [WritableState],
//       allowHalfOpen: true,
//       _maxListeners: undefined,
//       _eventsCount: 8,
//       _sockname: null,
//       _pendingData: null,
//       _pendingEncoding: '',
//       server: [Server],
//       _server: [Server],
//       parser: [HTTPParser],
//       on: [Function: socketListenerWrap],
//       addListener: [Function: socketListenerWrap],
//       prependListener: [Function: socketListenerWrap],
//       setEncoding: [Function: socketSetEncoding],
//       _paused: false,
//       _httpMessage: [Circular *3],
//       [Symbol(async_id_symbol)]: 17,
//       [Symbol(kHandle)]: [TCP],
//       [Symbol(lastWriteQueueSize)]: 0,
//       [Symbol(timeout)]: null,
//       [Symbol(kBuffer)]: null,
//       [Symbol(kBufferCb)]: null,
//       [Symbol(kBufferGen)]: null,
//       [Symbol(shapeMode)]: true,
//       [Symbol(kCapture)]: false,
//       [Symbol(kSetNoDelay)]: true,
//       [Symbol(kSetKeepAlive)]: false,
//       [Symbol(kSetKeepAliveInitialDelay)]: 0,
//       [Symbol(kBytesRead)]: 0,
//       [Symbol(kBytesWritten)]: 0
//     },
//     [Symbol(kOutHeaders)]: [Object: null prototype] { 'x-powered-by': [Array], etag: [Array] },
//     [Symbol(errored)]: null,
//     [Symbol(kHighWaterMark)]: 16384,
//     [Symbol(kRejectNonStandardBodyWrites)]: false,
//     [Symbol(kUniqueHeaders)]: null
//   },
//   next: [Function: next],
//   baseUrl: '',
//   originalUrl: '/',
//   _parsedUrl: Url {
//     protocol: null,
//     slashes: null,
//     auth: null,
//     host: null,
//     port: null,
//     hostname: null,
//     hash: null,
//     search: null,
//     query: null,
//     pathname: '/',
//     path: '/',
//     href: '/',
//     _raw: '/'
//   },
//   route: Route {
//     path: '/',
//     stack: [ [Layer] ],
//     methods: [Object: null prototype] { get: true }
//   },
//   params: [Object: null prototype] {},
//   [Symbol(shapeMode)]: true,
//   [Symbol(kCapture)]: false,
//   [Symbol(kHeaders)]: {
//     host: 'localhost:3000',
//     connection: 'keep-alive',
//     'cache-control': 'max-age=0',
//     'sec-ch-ua': '"Not:A-Brand";v="99", "Google Chrome";v="145", "Chromium";v="145"',
//     'sec-ch-ua-mobile': '?0',
//     'sec-ch-ua-platform': '"Windows"',
//     'upgrade-insecure-requests': '1',
//     'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36',
//     accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*;q=0.8,application/signed-exchange;v=b3;q=0.7',
//     'sec-fetch-site': 'none',
//     'sec-fetch-mode': 'navigate',
//     'sec-fetch-user': '?1',
//     'sec-fetch-dest': 'document',
//     'accept-encoding': 'gzip, deflate, br, zstd',
//     'accept-language': 'en-US,en;q=0.9',
//     'if-none-match': 'W/"c-QwzjTQIHJO11oZbfwq1nx3dy0Wk"'
//   },
//   [Symbol(kHeadersCount)]: 32,
//   [Symbol(kTrailers)]: null,
//   [Symbol(kTrailersCount)]: 0*/
